import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ContextProvider from "@/context/contextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
           <ContextProvider>
              <Navbar/>
                {children}
              <Footer/>
           </ContextProvider>
      </body>
    </html>
  );
}
